configuration: Release

image: Visual Studio 2022

cache:
  - '%LocalAppData%\NuGet\v3-cache -> **\*.csproj'

before_build:
  - dotnet restore --verbosity quiet

build:
  parallel: true
  verbosity: minimal

test_script:
  - dotnet test --configuration Release --no-build --collect="Code Coverage" src\Ninject.Tests
  - nuget install Microsoft.CodeCoverage -x -Verbosity quiet
  - for /f %%G in ('dir /b /s *.coverage') do Microsoft.CodeCoverage\build\netstandard1.0\CodeCoverage\CodeCoverage analyze /output:%%~dpnG.coverage.xml "%%G"

after_test:
  - ps: |
      $ProgressPreference = 'SilentlyContinue'
      Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
      .\codecov.exe -f *.coverage.xml

artifacts:
  - path: 'src\**\*.nupkg'
  - path: 'src\**\*.snupkg'

deploy:
  provider: NuGet
  api_key:
    secure: MgcHlxjQ6r/qVrOqrfPOqohB0KilPGA5ogx4/L6viXQGI7lj6k0HrmI+6dC9BnxI
  on:
    appveyor_repo_tag: true
