name: .Net CI - Windows
on: #[workflow_call]  # allow this workflow to be called from other workflows
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:  
  build:    
    runs-on: windows-latest
    steps:      
      - name: Harden Runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34
        with:
          egress-policy: block
          allowed-endpoints: >
            api.nuget.org:443
            dotnetbuilds.azureedge.net:443
            dotnetcli.azureedge.net:443
            dotnetcli.blob.core.windows.net:443
            github.com:443
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        ##run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
      #- name: Save test results
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: coverage
      #    path: test-results.trx
      - name: Test Reporter
        uses: dorny/test-reporter@v1.9.1
        with:
          name: DotNET Tests
          path: "**/test-results.trx"                            
          reporter: dotnet-trx
          fail-on-error: true
            
